---
- name: Make sure sshd is installed
  package:
    name: openssh-server

- name: Create sftp-dedicated group
  group:
    name: "{{ sftp_group }}"

- name: Delete users
  include_tasks: delete_user.yml
  with_items: "{{ sftp_users }}"
  loop_control:
    loop_var: sftp_user
    label: sftp_user.name
  when: sftp_user.state | default('present') == 'absent'

- name: Create users
  include_tasks: create_user.yml
  with_items: "{{ sftp_users }}"
  loop_control:
    loop_var: sftp_user
    label: sftp_user.name
  when: sftp_user.state | default('present') == 'present'

- name: Deploy extra sshd config
  template:
    src: sshd_config.j2
    dest: "{{ sftp_sshd_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: sshd reload

- name: Deploy sshd service config
  template:
    src: systemd_service.j2
    dest: "/lib/systemd/system/{{ sftp_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify: sshd reload

- name: Register & run service
  systemd:
    name: sshd_sftp
    state: started
    enabled: true
    daemon_reload: true
